image: cypress/browsers:node16.13.0-chrome95-ff94
options:
  max-time: 120

definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress

pipelines:
  default:
    - step:
        name: Install dependencies and compile
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn
          - yarn compile
          - yarn lint:fix
          - yarn cy:list:spec:by:names
          - yarn cy:list:spec:by:tags
    - step:
        name: Cypress - Chrome browser
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn cy:run:chrome
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/test-results/**
          - cypress/downloads/**
    - step:
        name: Cypress - Firefox browser
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn cy:run:firefox
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/test-results/**
          - cypress/downloads/**
