image: cypress/browsers:node14.17.0-chrome91-ff89
options:
  max-time: 120

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn
    - step:
        name: Cypress in Chrome only
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn cypress run --browser firefox --headless --spec 'cypress/integration/globalSystemSettings/statementManagement.spec.js'
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/test-results/**
          - cypress/downloads/**


definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress
