image: cypress/browsers:node16.5.0-chrome94-ff93
options:
  max-time: 120

definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress

pipelines:
  default:
    - step:
        name: Install dependencies and compile
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn
          - yarn compile
          - yarn lint:fix
    - step:
        name: Cypress - Chrome browser
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn cy:run:headless:mocha:chrome
          - yarn cy:posttest:results
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/test-results/**
          - cypress/downloads/**
    - step:
        name: Cypress - Firefox browser
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn cy:run:headless:mocha:firefox
          - yarn cy:posttest:results
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/test-results/**
          - cypress/downloads/**
