image: cypress/browsers:node12.14.1-chrome85-ff81
options:
  max-time: 10

pipelines:
  default:
  - step:
      name: Install dependencies
      caches:
        - npm
        - cypress
        - node
  - step:
      name: Running Cypress in Chrome only
      script:
        - yarn
        - yarn cy:run:chrome
  
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress