image: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
options:
  max-time: 15

definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress

pipelines:
  default:
    - step:
        name: Install dependencies and compile
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn
          - yarn compile
          - yarn lint:fix
          - yarn cy:list:spec:by:names
          - yarn cy:list:spec:by:tags
