image: cypress/browsers:node14.17.0-chrome91-ff89
options:
  max-time: 120

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn
    - step:
        name: Cypress in Chrome only
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn cy:run:headless:mocha
          - yarn cy:posttest:results
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/test-results/**
    - step:
        name: Cypress in Firefox only
        caches:
          - npm
          - cypress
          - node
        script:
          - cy:run:headless:mocha:firefox
          - yarn cy:posttest:results
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/test-results/**

definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress
